name: Pages Pipeline
on:
  push:
    branches: [master]
jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Startup test database instance
        run: sudo service mysql start
      - name: Create test database
        run: |
          chmod +x ./scripts/build-setup.sh
          bash ./scripts/build-setup.sh
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: build/libs/pages.jar
      - name: build-docker-image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/pages
          tags: db
  deploy-image-to-pks:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Pivnet & PKS
        run: |
          chmod +x ./scripts/kube-install.sh
          bash ./scripts/kube-install.sh ${{ secrets.PIVNET_API_TOKEN }}
      - name: PKS Login
        run: |
          pks login -a ${{ secrets.PKS_API }}  ${{ secrets.PKS_CLUSTER }} -u ${{ secrets.PKS_USERNAME }} -k -p ${{ secrets.PKS_PASSWORD }}
          pks get-credentials ${{ secrets.PKS_CLUSTER}}
      - name: Create and Update K8s Objects
        run: |
          chmod +x ./scripts/deploy-objects-to-k8s.sh
          bash ./scripts/deploy-objects-to-k8s.sh

